Alumni Page Updated
MicrosoftStudentChapter/mlsctiet pull request #94
Opened 2023-07-10 14:41 UTC by RijulBansal

2023-07-10 17:58 UTC, nimishmedatwal reviewed
Important changes:
- Change app.js in src so that your page can be rendered.
- Change the Navbar as well to show Alumini button
Minor changes: 
-  remove **all** the code that is commented also remove the two sample images.

2023-07-10 17:58 UTC, nimishmedatwal commented on src/Pages/Alumni/Components/Sampleimg.png
Remove this pic

2023-07-10 17:58 UTC, nimishmedatwal commented on src/Pages/Alumni/Assets/alumni.jpg
Remove this sample image

2023-07-10 17:58 UTC, nimishmedatwal commented on src/Pages/Alumni/Main.js
> +// import React, { useState } from "react";
Delete all the commented code.

2023-07-10 17:58 UTC, nimishmedatwal commented on src/Pages/Alumni/PolaroidGrid.js
> +// import React, { useEffect, useState } from "react";
Remove the commented code here also

2023-07-10 17:58 UTC, nimishmedatwal commented on src/Pages/Alumni/Styles/Style.module.css
> +/* @import url("https://fonts.googleapis.com/css2?family=Poppins&display=swap");
.

2023-07-10 17:58 UTC, nimishmedatwal commented on src/Pages/Alumni/Styles/PolaroidGrid.module.css
> +/* .image {
.

2023-07-10 17:58 UTC, nimishmedatwal commented on src/Pages/Alumni/Styles/PolaroidGrid.module.css
> +  /* opacity: 100%;  */
.

2023-07-10 17:58 UTC, nimishmedatwal commented on src/Pages/Alumni/Styles/Years.module.css
> +/* @import url("https://fonts.googleapis.com/css2?family=Poppins&display=swap");
.

2023-07-11 10:38 UTC, MankiratSingh1315 requested changes

2023-07-11 10:38 UTC, MankiratSingh1315 commented on src/Pages/Alumni/Styles/Card.module.css
> +html{
Don't apply font styling on html as it changes the styling of other pages too.

2023-07-12 09:24 UTC, MankiratSingh1315 commented
I have updated the images of 2022 alumni. Please make them fit in the carousel without shrinking.

2023-07-20 17:47 UTC, merged